### ISSUE TITLE
Rosdmap

### ISSUE THREAD

**Issue by joeblew99** [johanhenriksson/goworld#2]
Your roadmap is close to mine.
Thinking about extending on your work with regards to 2d text and native cut and paste and mobile integration.

Did you get to the point of 2d form layout logic yet ?
.do you want help or you left this for dead ?

Cheers

**Comment by joeblew99** [comment]
I am guessing this project is dead ?

Are you interested in it still because am liking what i am seeing and thinking of taking it further.


````
x-MacBook-Pro:goworld apple$ go build
# github.com/johanhenriksson/goworld/render
render/vertexarray.go:36: vao.Bind() used as value
render/vertexarray.go:40: missing return at end of function
x-MacBook-Pro:goworld apple$ 

````

**Comment by johanhenriksson** [comment]
Yeah it's pretty dead for now. I was using a go wrapper for the ODE physics engine but i couldn't get it to compile on newer versions of OSX i think.

I can take a look later and see if i can get the other stuff to run if you want to work on it :)

On 22 Jul 2017, at 13:51, jow blew <notifications@github.com<mailto:notifications@github.com>> wrote:


I am guessing this project is dead ?

Are you interested in it still because am liking what i am seeing and thinking of taking it further.

x-MacBook-Pro:goworld apple$ go build
# github.com/johanhenriksson/goworld/render<http://github.com/johanhenriksson/goworld/render>
render/vertexarray.go:36: vao.Bind() used as value
render/vertexarray.go:40: missing return at end of function
x-MacBook-Pro:goworld apple$

**Comment by joeblew99** [comment]
Hey :)

Well i might pull some of what you have done into this:
https://github.com/walesey/go-engine

you both pretty much were working on the same sort of things.
Walter has gotten a bit further.
